name: Minecraft Server

on:
  workflow_dispatch:   # 👈 isse tu manually run kar paayega
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Download Paper 1.21.4
        run: |
          mkdir server
          cd server
          curl -o paperclip.jar https://api.papermc.io/v2/projects/paper/versions/1.21.4/builds/32/downloads/paper-1.21.4-32.jar

      - name: Accept EULA
        run: |
          echo "eula=true" > server/eula.txt

      - name: Start Server
        run: |
          cd server
          java -Xmx2G -Xms1G -jar paperclip.jar nogui &

      - name: Start Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          ngrok tcp 25565
